version: "3.7"

secrets:
    smtp_user:
     external: true
    smtp_password:
     external: true
services:
  repmgr-checker:
    image: altipeak/repmgr-checker-service:dev
    restart: always
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    secrets:
            - smtp_user
            - smtp_password
    environment:
            - DATABASE_NAME=database
            - CHECK_FREQUENCY=60
            - EMAIL_NOTIFICATIONS=yes
            - RECIPIENTS=mauro.mercuri@altipeak.com
            - SMTP_SERVER=smtp.zoho.com
            - SMTP_PORT=587
            - SMTP_USER=automation@altipeaksecurity.com
            - SMTP_PASSWORD=0nGTdpt2VAzD
    deploy:
      replicas: 1
        #      placement:
              #        constraints: [node.hostname == MT-DEV-Node-LAN-1]
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
        #      restart_policy:
        #        condition: always
        #        delay: 10s
        #        max_attempts: 3
        #        window: 30s
      resources:
        limits:
          cpus: '0.05'
          memory: 20M
          #        reservations:
          #          cpus: '0.10'
          #          memory: 10M

