version: "3.7"

services:
  repmgr-checker:
    image: altipeak/repmgr-checker-service:dev
    restart: always
    volumes:
            - /var/run/docker.sock:/var/run/docker.sock
    secrets:
       - smtp_user
       - smtp_password
    environment:
            - CHECK_FREQUENCY=60
            - EMAIL_NOTIFICATION=yes
            - RECIPIENTS=mauro.mercuri@altipeak.com
            - SMTP_SERVER=smtp.zoho.com
            - SMTP_PORT=587
            - SMTP_USER=/run/secrets/smtp_user
            - SMTP_PASSWORD=/run/secrets/smtp_password
    deploy:
      replicas: 1
        #      placement:
              #        constraints: [node.hostname == MT-DEV-Node-LAN-1]
      update_config:
        parallelism: 1
        delay: 15s
        order: start-first
        #      restart_policy:
        #        condition: always
        #        delay: 10s
        #        max_attempts: 3
        #        window: 30s
      resources:
        limits:
          cpus: '0.05'
          memory: 20M
          #        reservations:
          #          cpus: '0.10'
          #          memory: 10M

